package routeros

import (
	"bytes"
	"fmt"
	"text/template"

	"mikrotik-psk-knock/client/internal/config"
)

type renderData struct {
	RouterName      string
	Service         string
	ClientID        string
	PSK             string
	Stage1Port      int
	Stage2Port      int
	TokenPort       int
	AllowedList     string
	StageTimeout    string
	TokenHitTimeout string
	AllowedTimeout  string
	UsedTimeout     string
	NotifyEnabled   string
	NotifyURL       string
	NATEnabled      string
	NATComment      string
	NATDstPort      int
	NATToAddress    string
	NATToPort       int
}

func Render(res config.Resolved) (string, error) {
	data := renderData{
		RouterName:      rosString(res.Config.Router.Name),
		Service:         rosString(res.Service.ServiceName),
		ClientID:        rosString(res.Client.ClientID),
		PSK:             rosString(res.Client.PSK),
		Stage1Port:      res.Service.Stage1Port,
		Stage2Port:      res.Service.Stage2Port,
		TokenPort:       res.Service.TokenPort,
		AllowedList:     rosString(res.Service.AllowedList),
		StageTimeout:    res.Config.Defaults.StageTimeout,
		TokenHitTimeout: res.Config.Defaults.TokenHitTimeout,
		AllowedTimeout:  res.Config.Defaults.AllowedTimeout,
		UsedTimeout:     res.Config.Defaults.UsedTimeout,
		NotifyEnabled:   rosBool(res.Service.Notify.Enabled),
		NotifyURL:       rosString(res.Service.Notify.URL),
		NATEnabled:      rosBool(res.Service.NAT.Enabled),
		NATComment:      rosString(res.Service.NAT.Comment),
		NATDstPort:      res.Service.NAT.DstPort,
		NATToAddress:    rosString(res.Service.NAT.ToAddress),
		NATToPort:       res.Service.NAT.ToPort,
	}

	var out bytes.Buffer
	if err := scriptTemplate.Execute(&out, data); err != nil {
		return "", err
	}
	return out.String(), nil
}

func rosBool(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func rosString(v string) string {
	var out bytes.Buffer
	out.WriteByte('"')
	for _, r := range v {
		switch r {
		case '\\':
			out.WriteString("\\\\")
		case '"':
			out.WriteString("\\\"")
		case '\n', '\r':
			out.WriteByte(' ')
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}

var scriptTemplate = template.Must(template.New("routeros").Parse(fmt.Sprintf(`# Generated by mkpk routeros render.
# This renders one client/service into the currently verified single-profile RouterOS scheme.

/system scheduler remove [find where name~"^mkpk-tt-"]
/system script remove [find where name~"^mkpk-tt-"]
/ip firewall filter remove [find where comment~"^mkpk-tt "]
/ip firewall nat remove [find where comment~"^mkpk-tt "]
/ip firewall address-list remove [find where list~"^mkpk-tt-"]

/system script
add name="mkpk-tt-profile-demo" policy=read,write,test source={
    :global mkpkTtService {{.Service}}
    :global mkpkTtClientId {{.ClientID}}
    :global mkpkTtPsk {{.PSK}}
    :global mkpkTtTokenPort {{.TokenPort}}
    :global mkpkTtAllowedList {{.AllowedList}}
    :global mkpkTtAllowedTimeout "{{.AllowedTimeout}}"
    :global mkpkTtUsedTimeout "{{.UsedTimeout}}"
    :global mkpkTtNotifyEnabled {{.NotifyEnabled}}
    :global mkpkTtNotifyUrl {{.NotifyURL}}
    :global mkpkTtNatEnabled {{.NATEnabled}}
    :global mkpkTtNatComment {{.NATComment}}
    :global mkpkTtNatDstPort {{.NATDstPort}}
    :global mkpkTtNatToAddress {{.NATToAddress}}
    :global mkpkTtNatToPort {{.NATToPort}}
}

/ip firewall filter
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.Stage1Port}} \
    address-list=mkpk-tt-stage1 address-list-timeout={{.StageTimeout}} \
    comment="mkpk-tt stage1"
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.Stage2Port}} \
    src-address-list=mkpk-tt-stage1 \
    address-list=mkpk-tt-stage2 address-list-timeout={{.StageTimeout}} \
    comment="mkpk-tt stage2"
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.TokenPort}} \
    src-address-list=mkpk-tt-stage2 content="mkpk-tt-token-not-initialized" \
    address-list=mkpk-tt-token-hit-now address-list-timeout={{.TokenHitTimeout}} disabled=yes \
    comment="mkpk-tt token now"
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.TokenPort}} \
    src-address-list=mkpk-tt-stage2 content="mkpk-tt-token-not-initialized" \
    address-list=mkpk-tt-token-hit-prev address-list-timeout={{.TokenHitTimeout}} disabled=yes \
    comment="mkpk-tt token prev"

%s
`, tailTemplate)))

const tailTemplate = `/system script
add name="mkpk-tt-apply-service" policy=read,write,test source={
    /system script run mkpk-tt-profile-demo

    :global mkpkTtAllowedList
    :global mkpkTtNatEnabled
    :global mkpkTtNatComment
    :global mkpkTtNatDstPort
    :global mkpkTtNatToAddress
    :global mkpkTtNatToPort

    :local natDisabled true
    :if ($mkpkTtNatEnabled = true) do={
        :set natDisabled false
    }

    :local natRule [/ip firewall nat find where comment=$mkpkTtNatComment]
    :if ([:len $natRule] = 0) do={
        /ip firewall nat add chain=dstnat action=dst-nat protocol=tcp \
            dst-port=$mkpkTtNatDstPort src-address-list=$mkpkTtAllowedList \
            to-addresses=$mkpkTtNatToAddress to-ports=$mkpkTtNatToPort \
            disabled=$natDisabled comment=$mkpkTtNatComment
        :log info ("mkpk-tt service nat created comment=" . $mkpkTtNatComment)
    } else={
        /ip firewall nat set $natRule chain=dstnat action=dst-nat protocol=tcp \
            dst-port=$mkpkTtNatDstPort src-address-list=$mkpkTtAllowedList \
            to-addresses=$mkpkTtNatToAddress to-ports=$mkpkTtNatToPort \
            disabled=$natDisabled
        :log info ("mkpk-tt service nat updated comment=" . $mkpkTtNatComment)
    }
}

add name="mkpk-tt-notify" policy=read,write,test source={
    :global mkpkTtNotifyEnabled
    :global mkpkTtNotifyUrl
    :global mkpkTtNotifyRouter
    :global mkpkTtNotifyService
    :global mkpkTtNotifyClientId
    :global mkpkTtNotifySrc
    :global mkpkTtNotifyList
    :global mkpkTtNotifyTtl
    :global mkpkTtNotifyBucket
    :global mkpkTtNotifyTime

    :if ($mkpkTtNotifyEnabled != true) do={
        :return 0
    }
    :if ([:len $mkpkTtNotifyUrl] = 0) do={
        :log warning "mkpk-tt notify enabled but url is empty"
        :return 0
    }

    :local payload ("router=" . $mkpkTtNotifyRouter . "&service=" . $mkpkTtNotifyService . "&client_id=" . $mkpkTtNotifyClientId . "&src=" . $mkpkTtNotifySrc . "&list=" . $mkpkTtNotifyList . "&ttl=" . $mkpkTtNotifyTtl . "&mode=udp-token&bucket=" . $mkpkTtNotifyBucket . "&time=" . $mkpkTtNotifyTime)
    :do {
        /tool fetch url=$mkpkTtNotifyUrl http-method=post http-data=$payload keep-result=no
    } on-error={
        :log warning ("mkpk-tt notify failed src=" . $mkpkTtNotifySrc . " service=" . $mkpkTtNotifyService)
    }
    :return 0
}

add name="mkpk-tt-poller" policy=read,write,test source={
    /system script run mkpk-tt-profile-demo

    :global mkpkTtService
    :global mkpkTtClientId
    :global mkpkTtPsk
    :global mkpkTtTokenPort
    :global mkpkTtAllowedList
    :global mkpkTtAllowedTimeout
    :global mkpkTtUsedTimeout

    :local service $mkpkTtService
    :local clientId $mkpkTtClientId
    :local psk $mkpkTtPsk
    :local tokenPort $mkpkTtTokenPort
    :local allowedList $mkpkTtAllowedList
    :local allowedTimeout $mkpkTtAllowedTimeout
    :local usedTimeout $mkpkTtUsedTimeout
    :local nowBucket ([:timestamp] / 30s)
    :local prevBucket ($nowBucket - 1)

    :local nowMsg ($psk . "|v1|" . $service . "|" . $clientId . "|" . $nowBucket . "|" . $psk)
    :local prevMsg ($psk . "|v1|" . $service . "|" . $clientId . "|" . $prevBucket . "|" . $psk)
    :local nowToken [:convert $nowMsg from=raw to=hex transform=sha512]
    :local prevToken [:convert $prevMsg from=raw to=hex transform=sha512]

    :local nowRule [/ip firewall filter find where comment="mkpk-tt token now"]
    :local prevRule [/ip firewall filter find where comment="mkpk-tt token prev"]

    :if (([:len $nowRule] = 0) || ([:len $prevRule] = 0)) do={
        :log error "mkpk-tt token rules missing; fail-closed"
        :return 0
    }

    :if ([/ip firewall filter get $nowRule content] != $nowToken) do={
        /ip firewall filter set $nowRule content=$nowToken disabled=no dst-port=$tokenPort
    }
    :if ([/ip firewall filter get $prevRule content] != $prevToken) do={
        /ip firewall filter set $prevRule content=$prevToken disabled=no dst-port=$tokenPort
    }

    :local nowHits [/ip firewall address-list find where list="mkpk-tt-token-hit-now"]
    :local prevHits [/ip firewall address-list find where list="mkpk-tt-token-hit-prev"]
    :local hitCount ([:len $nowHits] + [:len $prevHits])

    :if ($hitCount = 0) do={
        :return 0
    }

    :local selectedBucket $nowBucket
    :local selectedHits $nowHits

    :if (([:len $nowHits] = 0) && ([:len $prevHits] > 0)) do={
        :set selectedBucket $prevBucket
        :set selectedHits $prevHits
    }

    :local usedList ("mkpk-tt-used-" . $selectedBucket)
    :local used [/ip firewall address-list find where list=$usedList]

    :if ([:len $used] > 0) do={
        :log warning ("mkpk-tt replay ignored; bucket already used; hits=" . $hitCount)
        /ip firewall address-list remove $nowHits
        /ip firewall address-list remove $prevHits
        :return 0
    }

    :if ($hitCount > 1) do={
        /ip firewall address-list add list=$usedList address=127.0.0.1 timeout=$usedTimeout comment=("bucket=" . $selectedBucket)
        :log warning ("mkpk-tt collision/replay suspicion; hits=" . $hitCount . "; bucket burned")
        /ip firewall address-list remove $nowHits
        /ip firewall address-list remove $prevHits
        :return 0
    }

    :local hit [:pick $selectedHits 0]
    :local src [/ip firewall address-list get $hit address]

    /ip firewall address-list add list=$usedList address=127.0.0.1 timeout=$usedTimeout comment=("bucket=" . $selectedBucket)
    /ip firewall address-list remove [find where list=$allowedList address=$src]
    /ip firewall address-list add list=$allowedList address=$src timeout=$allowedTimeout \
        comment=("mkpk-tt client_id=" . $clientId . "; mode=udp-token; service=" . $service . "; bucket=" . $selectedBucket)
    :log info ("mkpk-tt allowed src=" . $src . " ttl=" . $allowedTimeout . " bucket=" . $selectedBucket)
    /ip firewall address-list remove $nowHits
    /ip firewall address-list remove $prevHits

    :global mkpkTtNotifyRouter [/system identity get name]
    :global mkpkTtNotifyService $service
    :global mkpkTtNotifyClientId $clientId
    :global mkpkTtNotifySrc $src
    :global mkpkTtNotifyList $allowedList
    :global mkpkTtNotifyTtl $allowedTimeout
    :global mkpkTtNotifyBucket $selectedBucket
    :global mkpkTtNotifyTime [:timestamp]
    /system script run mkpk-tt-notify
    :return 0
}

add name="mkpk-tt-startup" policy=read,write,test source={
    :local invalidContent "mkpk-tt-token-not-initialized"
    :local nowRule [/ip firewall filter find where comment="mkpk-tt token now"]
    :local prevRule [/ip firewall filter find where comment="mkpk-tt token prev"]

    :if ([:len $nowRule] > 0) do={
        /ip firewall filter set $nowRule content=$invalidContent disabled=yes
    }
    :if ([:len $prevRule] > 0) do={
        /ip firewall filter set $prevRule content=$invalidContent disabled=yes
    }

    /ip firewall address-list remove [find where list~"^mkpk-tt-token-hit"]
    /system script run mkpk-tt-apply-service
    /system script run mkpk-tt-poller
    :log info "mkpk-tt startup guard applied"
    :return 0
}

/system scheduler
add name="mkpk-tt-startup" start-time=startup \
    on-event="/system script run mkpk-tt-startup" \
    policy=read,write,test comment="mkpk-tt fail-closed startup guard"
add name="mkpk-tt-poller" interval=1s start-time=startup \
    on-event="/system script run mkpk-tt-poller" \
    policy=read,write,test comment="mkpk-tt update tokens and poll hits"
add name="mkpk-tt-install" interval=1s \
    on-event="/system scheduler remove [find where name=\"mkpk-tt-install\"]; /system script run mkpk-tt-startup" \
    policy=read,write,test comment="mkpk-tt one-shot post-import init"

/system script run mkpk-tt-apply-service
:log info "mkpk-tt installed"
`
