package routeros

import (
	"bytes"
	"fmt"
	"sort"
	"text/template"

	"mikrotik-psk-knock/client/internal/config"
)

type svcData struct {
	Key          string
	Stage1Port   int
	Stage2Port   int
	TokenPort    int
	AllowedList  string // plain, validated safe name
	NATDisabled  string // "yes" / "no"
	NATComment   string // ros-quoted
	NATDstPort   int
	NATToAddress string // ros-quoted
	NATToPort    int
}

type cliData struct {
	Key            string
	ServiceKey     string
	Service        string // ros-quoted service_name
	ClientID       string // ros-quoted
	PSK            string // ros-quoted
	TokenPort      int
	AllowedList    string // plain, validated safe name
	AllowedListStr string // ros-quoted
	AllowedTimeout string // plain
	UsedTimeout    string // plain
	NotifyEnabled  string // "true" / "false"
	NotifyURL      string // ros-quoted
}

type renderConfigData struct {
	BucketSeconds   int64
	StageTimeout    string
	TokenHitTimeout string
	Services        []svcData
	Clients         []cliData
}

// RenderConfig renders every service and client in cfg into per-profile RouterOS
// objects. cfg is expected to be already validated (config.Load validates it).
func RenderConfig(cfg config.Config) (string, error) {
	data := renderConfigData{
		BucketSeconds:   cfg.Defaults.BucketSeconds,
		StageTimeout:    cfg.Defaults.StageTimeout,
		TokenHitTimeout: cfg.Defaults.TokenHitTimeout,
	}

	for _, k := range sortedKeys(cfg.Services) {
		s := cfg.Services[k]
		data.Services = append(data.Services, svcData{
			Key:          k,
			Stage1Port:   s.Stage1Port,
			Stage2Port:   s.Stage2Port,
			TokenPort:    s.TokenPort,
			AllowedList:  s.AllowedList,
			NATDisabled:  rosDisabled(s.NAT.Enabled),
			NATComment:   rosString(s.NAT.Comment),
			NATDstPort:   s.NAT.DstPort,
			NATToAddress: rosString(s.NAT.ToAddress),
			NATToPort:    s.NAT.ToPort,
		})
	}

	for _, k := range sortedKeys(cfg.Clients) {
		c := cfg.Clients[k]
		s, ok := cfg.Services[c.Service]
		if !ok {
			return "", fmt.Errorf("client %q references unknown service %q", k, c.Service)
		}
		data.Clients = append(data.Clients, cliData{
			Key:            k,
			ServiceKey:     c.Service,
			Service:        rosString(s.ServiceName),
			ClientID:       rosString(c.ClientID),
			PSK:            rosString(c.PSK),
			TokenPort:      s.TokenPort,
			AllowedList:    s.AllowedList,
			AllowedListStr: rosString(s.AllowedList),
			AllowedTimeout: cfg.Defaults.AllowedTimeout,
			UsedTimeout:    cfg.Defaults.UsedTimeout,
			NotifyEnabled:  rosBool(s.Notify.Enabled),
			NotifyURL:      rosString(s.Notify.URL),
		})
	}

	var out bytes.Buffer
	if err := configTemplate.Execute(&out, data); err != nil {
		return "", err
	}
	return out.String(), nil
}

// Render keeps the single-client entry point by rendering a config that contains
// only the resolved service and client.
func Render(res config.Resolved) (string, error) {
	serviceKey := res.Client.Service
	if serviceKey == "" {
		serviceKey = res.Service.ServiceName
	}
	clientKey := res.Client.ClientID
	cfg := res.Config
	cfg.Services = map[string]config.Service{serviceKey: res.Service}
	cfg.Clients = map[string]config.Client{clientKey: {
		ClientID: res.Client.ClientID,
		Service:  serviceKey,
		PSK:      res.Client.PSK,
	}}
	return RenderConfig(cfg)
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func rosBool(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func rosDisabled(enabled bool) string {
	if enabled {
		return "no"
	}
	return "yes"
}

func rosString(v string) string {
	var out bytes.Buffer
	out.WriteByte('"')
	for _, r := range v {
		switch r {
		case '\\':
			out.WriteString("\\\\")
		case '"':
			out.WriteString("\\\"")
		case '\n', '\r':
			out.WriteByte(' ')
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}

var configTemplate = template.Must(template.New("routeros").Parse(`# Generated by mkpk-provision routeros render (multi-profile).
# Renders all services and clients from the mkpk config into per-profile RouterOS objects.

/system scheduler remove [find where name~"^mkpk-tt-"]
/system script remove [find where name~"^mkpk-tt-"]
/ip firewall filter remove [find where comment~"^mkpk-tt "]
/ip firewall nat remove [find where comment~"^mkpk-tt "]
/ip firewall address-list remove [find where list~"^mkpk-tt-"]

/ip firewall filter
{{range .Services}}add chain=input action=add-src-to-address-list protocol=udp dst-port={{.Stage1Port}} \
    address-list=mkpk-tt-stage1-{{.Key}} address-list-timeout={{$.StageTimeout}} \
    comment="mkpk-tt stage1 {{.Key}}"
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.Stage2Port}} \
    src-address-list=mkpk-tt-stage1-{{.Key}} \
    address-list=mkpk-tt-stage2-{{.Key}} address-list-timeout={{$.StageTimeout}} \
    comment="mkpk-tt stage2 {{.Key}}"
{{end}}{{range .Clients}}add chain=input action=add-src-to-address-list protocol=udp dst-port={{.TokenPort}} \
    src-address-list=mkpk-tt-stage2-{{.ServiceKey}} content="mkpk-tt-token-not-initialized" \
    address-list=mkpk-tt-hit-now-{{.Key}} address-list-timeout={{$.TokenHitTimeout}} disabled=yes \
    comment="mkpk-tt token now {{.Key}}"
add chain=input action=add-src-to-address-list protocol=udp dst-port={{.TokenPort}} \
    src-address-list=mkpk-tt-stage2-{{.ServiceKey}} content="mkpk-tt-token-not-initialized" \
    address-list=mkpk-tt-hit-prev-{{.Key}} address-list-timeout={{$.TokenHitTimeout}} disabled=yes \
    comment="mkpk-tt token prev {{.Key}}"
{{end}}
/system script
add name="mkpk-tt-apply-service" policy=read,write,test source={
{{range .Services}}    :if ([:len [/ip firewall nat find where comment={{.NATComment}}]] = 0) do={
        /ip firewall nat add chain=dstnat action=dst-nat protocol=tcp dst-port={{.NATDstPort}} \
            src-address-list={{.AllowedList}} to-addresses={{.NATToAddress}} to-ports={{.NATToPort}} \
            disabled={{.NATDisabled}} comment={{.NATComment}}
        :log info ("mkpk-tt service nat created comment=" . {{.NATComment}})
    } else={
        /ip firewall nat set [/ip firewall nat find where comment={{.NATComment}}] chain=dstnat action=dst-nat protocol=tcp dst-port={{.NATDstPort}} \
            src-address-list={{.AllowedList}} to-addresses={{.NATToAddress}} to-ports={{.NATToPort}} disabled={{.NATDisabled}}
        :log info ("mkpk-tt service nat updated comment=" . {{.NATComment}})
    }
{{end}}}

add name="mkpk-tt-notify" policy=read,write,test source={
    :global mkpkTtNotifyEnabled
    :global mkpkTtNotifyUrl
    :global mkpkTtNotifyRouter
    :global mkpkTtNotifyService
    :global mkpkTtNotifyClientId
    :global mkpkTtNotifySrc
    :global mkpkTtNotifyList
    :global mkpkTtNotifyTtl
    :global mkpkTtNotifyBucket
    :global mkpkTtNotifyTime

    :if ($mkpkTtNotifyEnabled != true) do={
        :return 0
    }
    :if ([:len $mkpkTtNotifyUrl] = 0) do={
        :log warning "mkpk-tt notify enabled but url is empty"
        :return 0
    }

    :local payload ("router=" . $mkpkTtNotifyRouter . "&service=" . $mkpkTtNotifyService . "&client_id=" . $mkpkTtNotifyClientId . "&src=" . $mkpkTtNotifySrc . "&list=" . $mkpkTtNotifyList . "&ttl=" . $mkpkTtNotifyTtl . "&mode=udp-token&bucket=" . $mkpkTtNotifyBucket . "&time=" . $mkpkTtNotifyTime)
    :do {
        /tool fetch url=$mkpkTtNotifyUrl http-method=post http-data=$payload keep-result=no
    } on-error={
        :log warning ("mkpk-tt notify failed src=" . $mkpkTtNotifySrc . " service=" . $mkpkTtNotifyService)
    }
    :return 0
}

{{range .Clients}}add name="mkpk-tt-poller-{{.Key}}" policy=read,write,test source={
    :local service {{.Service}}
    :local clientId {{.ClientID}}
    :local psk {{.PSK}}
    :local tokenPort {{.TokenPort}}
    :local allowedList {{.AllowedListStr}}
    :local allowedTimeout "{{.AllowedTimeout}}"
    :local usedTimeout "{{.UsedTimeout}}"
    :local notifyEnabled {{.NotifyEnabled}}
    :local notifyUrl {{.NotifyURL}}
    :local nowBucket ([:timestamp] / {{$.BucketSeconds}}s)
    :local prevBucket ($nowBucket - 1)

    :local nowMsg ($psk . "|v1|" . $service . "|" . $clientId . "|" . $nowBucket . "|" . $psk)
    :local prevMsg ($psk . "|v1|" . $service . "|" . $clientId . "|" . $prevBucket . "|" . $psk)
    :local nowToken [:convert $nowMsg from=raw to=hex transform=sha512]
    :local prevToken [:convert $prevMsg from=raw to=hex transform=sha512]

    :local nowRule [/ip firewall filter find where comment="mkpk-tt token now {{.Key}}"]
    :local prevRule [/ip firewall filter find where comment="mkpk-tt token prev {{.Key}}"]

    :if (([:len $nowRule] = 0) || ([:len $prevRule] = 0)) do={
        :log error "mkpk-tt token rules missing for {{.Key}}; fail-closed"
        :return 0
    }

    :if ([/ip firewall filter get $nowRule content] != $nowToken) do={
        /ip firewall filter set $nowRule content=$nowToken disabled=no dst-port=$tokenPort
    }
    :if ([/ip firewall filter get $prevRule content] != $prevToken) do={
        /ip firewall filter set $prevRule content=$prevToken disabled=no dst-port=$tokenPort
    }

    :local nowHits [/ip firewall address-list find where list="mkpk-tt-hit-now-{{.Key}}"]
    :local prevHits [/ip firewall address-list find where list="mkpk-tt-hit-prev-{{.Key}}"]
    :local hitCount ([:len $nowHits] + [:len $prevHits])

    :if ($hitCount = 0) do={
        :return 0
    }

    :local selectedBucket $nowBucket
    :local selectedHits $nowHits

    :if (([:len $nowHits] = 0) && ([:len $prevHits] > 0)) do={
        :set selectedBucket $prevBucket
        :set selectedHits $prevHits
    }

    :local usedList ("mkpk-tt-used-{{.Key}}-" . $selectedBucket)
    :local used [/ip firewall address-list find where list=$usedList]

    :if ([:len $used] > 0) do={
        :log warning ("mkpk-tt replay ignored for {{.Key}}; bucket already used; hits=" . $hitCount)
        /ip firewall address-list remove $nowHits
        /ip firewall address-list remove $prevHits
        :return 0
    }

    :if ($hitCount > 1) do={
        /ip firewall address-list add list=$usedList address=127.0.0.1 timeout=$usedTimeout comment=("bucket=" . $selectedBucket)
        :log warning ("mkpk-tt collision/replay suspicion for {{.Key}}; hits=" . $hitCount . "; bucket burned")
        /ip firewall address-list remove $nowHits
        /ip firewall address-list remove $prevHits
        :return 0
    }

    :local hit [:pick $selectedHits 0]
    :local src [/ip firewall address-list get $hit address]

    /ip firewall address-list add list=$usedList address=127.0.0.1 timeout=$usedTimeout comment=("bucket=" . $selectedBucket)
    /ip firewall address-list remove [find where list=$allowedList address=$src]
    /ip firewall address-list add list=$allowedList address=$src timeout=$allowedTimeout \
        comment=("mkpk-tt client_id=" . $clientId . "; mode=udp-token; service=" . $service . "; bucket=" . $selectedBucket)
    :log info ("mkpk-tt allowed src=" . $src . " ttl=" . $allowedTimeout . " bucket=" . $selectedBucket . " client={{.Key}}")
    /ip firewall address-list remove $nowHits
    /ip firewall address-list remove $prevHits

    :global mkpkTtNotifyEnabled $notifyEnabled
    :global mkpkTtNotifyUrl $notifyUrl
    :global mkpkTtNotifyRouter [/system identity get name]
    :global mkpkTtNotifyService $service
    :global mkpkTtNotifyClientId $clientId
    :global mkpkTtNotifySrc $src
    :global mkpkTtNotifyList $allowedList
    :global mkpkTtNotifyTtl $allowedTimeout
    :global mkpkTtNotifyBucket $selectedBucket
    :global mkpkTtNotifyTime [:timestamp]
    /system script run mkpk-tt-notify
    :return 0
}
{{end}}
add name="mkpk-tt-startup" policy=read,write,test source={
    :local invalidContent "mkpk-tt-token-not-initialized"
    :foreach rule in=[/ip firewall filter find where comment~"^mkpk-tt token "] do={
        /ip firewall filter set $rule content=$invalidContent disabled=yes
    }
    /ip firewall address-list remove [find where list~"^mkpk-tt-hit-"]
    /system script run mkpk-tt-apply-service
    :log info "mkpk-tt startup guard applied"
    :return 0
}

/system scheduler
add name="mkpk-tt-startup" start-time=startup \
    on-event="/system script run mkpk-tt-startup" \
    policy=read,write,test comment="mkpk-tt fail-closed startup guard"
{{range .Clients}}add name="mkpk-tt-poller-{{.Key}}" interval=1s start-time=startup \
    on-event="/system script run mkpk-tt-poller-{{.Key}}" \
    policy=read,write,test comment="mkpk-tt poll {{.Key}}"
{{end}}add name="mkpk-tt-install" interval=1s \
    on-event="/system scheduler remove [find where name=\"mkpk-tt-install\"]; /system script run mkpk-tt-startup" \
    policy=read,write,test comment="mkpk-tt one-shot post-import init"

/system script run mkpk-tt-apply-service
:log info "mkpk-tt installed"
`))
